output:
  csv_file: true
  json_file: true
  text_interpretation: true
  extract_bulk: false

llm:
  provider: AzureChatOpenAI  # Options: AzureChatOpenAI, ChatOllama
  azure:
    temperature: 0  # Other Azure-specific params
  ollama:
    model: "llama3.2:3b"
    temperature: 0
#    num_predict: 256

prompts:
  stuff_dlis_header_paragraph_summary:
    system: "You are an oil and gas upstream industry expert with expertise in well log interpretation and analysis."
    human: "Can you summarize the following details {user_input} from the headers of the one of the logical file from DLIS well log file."
  stuff_dlis_sections_paragraph_summary:
    system: "You are an oil and gas upstream industry expert with expertise in well log interpretation and analysis."
    human: "Can you summarize the following details {user_input} from the {section} of the one of the logical file from DLIS well log file."